### ISSUE TITLE
Swapping Weapons While Reloading

### ISSUE THREAD

**Issue by just32** [jwcorle/425_FinalProject#18]
Bug:
If the player switches weapons while reloading, the weapon that is swapped out breaks. If ammo was at 0, you can no longer reload. Also, the reload animation becomes stuck mid-animation. It is more obvious on the P90 than the pistol.

Objective:
Allow player to switch weapons while reloading without breaking the guns.

**Comment by co-go** [comment]
I rolled back my local repo to my last commit (70d2627bf0c2d63d2f72ba953479d4cb4fe07a48) and I couldn't replicate the weapon breaking. The animation was still bugged, but the gun would still reload. Something you added in the commits following broke the weapon reload when swapping.

**Comment by co-go** [comment]
Animations were resolved by adding in a default idle animation (which was just a transform = 0,0,0 keyframe) to the Pistol and P90 controllers. 

The reloading bug had to do with how you handled swapping the weapons (possibly due to the coroutine)? I just moved the CancelReload() into the Unity extensions [`OnEnable`](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnEnable.html) and [`OnDisable`](https://docs.unity3d.com/ScriptReference/MonoBehaviour.OnDisable.html). This means to swap weapons now, we only have to disable the current weapon and activate the second one from the `InventoryController`.
